name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup git config
        run: |
          git config user.name "Sadanand Pai"
          git config user.email "sadypai@gmail.com"

      - name: NPM installation
        run: npm install

      - name: Lint check
        run: npm run lint

      - name: Unit & E2E testing
        run: |
          npm test
          npm run e2e:test

      - name: Build setup
        run: |
          rm -rf dist
          npm run build
          git add dist -f

      - name: Commit & push
        run: git diff --staged --quiet || (git commit -m "build files - github action" && git push)
